# Generated by Django 5.2.7 on 2025-10-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products_for_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(max_length=100)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_image', models.ImageField(blank=True, null=True, upload_to='sale_products/')),
            ],
        ),
    ]
